<?php
/**
 *  Oksa Request.
 *
 * @author    Oksana Borodina
 * @copyright 2020.
 *
 */
?>

<span class="normal-price">
    <button class="action primary request-button"
            data-trigger=trigger
            id="request_button">
        <?= $block->escapeHtml(__('Request Price')); ?>
    </button>
</span>

<div class="product-request-popup" id="request_popup" style="display: none">
    <form class="request-form"
          id="request_form"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" >
        <fieldset class="fieldset">
            <div class="field request-name">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                           placeholder="Enter Your Name"
                           data-validate="{required: true}"
                           class="input-text" type="text"/>
                </div>
            </div>
            <div class="field request-email">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           placeholder="<?= $block->escapeHtmlAttr(__('Enter Your Email')) ?>"
                           class="input-text" type="text"
                           data-validate="{required: true, 'validate-email': true}"/>
                </div>
            </div>
            <div class="field request-comment">
                <label class="label"
                       for="comment"><span><?= $block->escapeHtml(__('Comment')) ?></span></label>
                <div class="control">
                    <textarea name="comment" id="comment" cols="5" rows="3"
                              title="<?= $block->escapeHtmlAttr(__('Comment')) ?>"
                              placeholder="<?= $block->escapeHtmlAttr(__('Enter Your Comment')) ?>"></textarea>
                </div>
            </div>
            <input name="sku" value="" type="text" hidden/>
        </fieldset>
    </form>
</div>

<script type="text/x-magento-init">
{
    "#request_form": {
        "validation": {}
    },
    "*": {
        "formRequest": {}
    }
}
</script>
